-- Supabase is used ONLY for Google sign-in (auth), not for storing data.
-- No tables, no SQL setup needed here — trade data lives in Cloudflare D1
-- instead (see trades-api/schema.sql), reached through a Worker that verifies
-- the Supabase-issued JWT itself (via Supabase's public JWKS endpoint).
--
-- To finish auth setup, in the Supabase dashboard:
--   1. Authentication > Sign In / Providers > enable Google, with a Google
--      Cloud OAuth Client ID/Secret.
--   2. Authentication > URL Configuration > set Site URL and Redirect URLs
--      to https://vivekbhandari.github.io/Option-buddy2.0/
--   3. Send the Project URL and anon (public) key so they can be filled
--      into js/auth.js.
--
-- See trades-api/README.md for the Cloudflare D1 side of setup.
